version: '3.3'

services: 
  mongo:
    image: mongo
    env_file:
      - ./.env
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/mongo:/data/db
    ports:
      - ${MONGODB_OUT_PORT}:27017

  redis:
    image: redis:alpine
    env_file:
      - ./.env
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_OUT_PORT}:6379


  bot: 
    build: .
    depends_on: 
      - mongo
      - redis
    restart: always
    env_file: 
      - ./.env
    volumes:
      - ${VOLUMES_PATH}/files:/app/files

  nginx:
    image: nginx
    env_file:
      - .env
    ports: 
      - ${FILES_PORT}:80
    volumes: 
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ${VOLUMES_PATH}/logs/nginx:/var/log/nginx
      - ${VOLUMES_PATH}/files:/usr/share/nginx/html
    depends_on: 
      - bot