version: '3.3'

services: 
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./volumes_data/mongo:/data/db
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:27017
  redis:
    image: redis:alpine
    env_file:
      - .env
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    restart: always